### ISSUE TITLE
TrackComponent - Station / PassengerCart - Engine probléma

### ISSUE THREAD

**Issue by najibghadri** [najibghadri/I-LIKE-TRAINS#1]
Minden TrackComponent-nek van hasStation() metódusa, és Station referenciája, ez nem jó, nem hatákony.
Másik probléma: Engine és a PassengerC hogy fogja intézni a leszállítást?

**Comment by daunera** [comment]
Én főként a másik problémára fókuszálnék. Az hogy sok a null nem a világ vége.

Leszállítás:
Csütörtökön abban egyeztünk meg, hogy lehetne egyedül akkor leszállás amikor a mozdony az állomáshoz ér. Így sokat ellenőrzést spórolunk. Én ezek alapján simán mondanám, hogy a passengerCart teljesen dummy és a teljes leszállítás logika az engine-ben legyen.

**Comment by daunera** [comment]
Ha az Engine checkStation() fgv-je pozitív jelzést ad vissza, akkor futhatna egy getingOffPaddanger() vagy hopOut() vagy valami ilyesmi függvény, ami elindul a list<passengerCart> elején és ellenőrzi az első nem üres utaskocsit, hogy egyezik-e a színe az állomással. Ha igen, akkor szépen kinulláza az utasszámot, ha pedig nem egyezik a színe, nem csinál semmit. Hogy ezt tudja ellenőrizni kell egy getColor és egy getPassangerNum() függvény, illetve egy setPassangerNum() vagy nullPassanger() vagy vmi ilyesmi néven a passengerCart-nak, amiket meghív
